title: # Name of your blog (this will show up at the top of your page and in the RSS feed)
  My Albums

author: # Your name, as you want it to appear underneath each post and in the footer
  Adrien Joly

avatar: # URL of your avatar or profile pic (you could use your GitHub profile pic)
  /icon.png

desc: Collection of music records I love, maintained with Jekyll on Github Pages

keywords: music, albums, records, collection, jekyll, static-web

repository: adrienjoly/album-shelf

google_analytics: UA-1858235-4

twitter: # used by the jekyll seo plugin
  username: adrienjoly
  card: summary

social:
  name: Adrien Joly
  links:
    - https://twitter.com/adrienjoly
    - https://www.linkedin.com/in/adrienjoly
    - https://github.com/adrienjoly
    - https://medium.com/@adrienjoly

defaults:
  - scope:
      path: ""
    values:
      image: "/logo.png"
      author: "@adrienjoly"

# github defaults
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# additional config
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - src

plugins:
  - jekyll-seo-tag
